### ISSUE TITLE
NPM install error

### ISSUE THREAD

**Issue by MAlwaz** [qiime2/q2view-old#124]
npm install produces an error
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: q2view@0.0.0
npm ERR! Found: redux@3.7.2
npm ERR! node_modules/redux
npm ERR!   redux@"^3.6.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer redux@"^4" from redux-thunk@2.4.1
npm ERR! node_modules/redux-thunk
npm ERR!   redux-thunk@"^2.1.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /home/smoke/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/smoke/.npm/_logs/2022-06-23T15_06_25_050Z-debug-0.log
```
complete error log
```
cat  /home/smoke/.npm/_logs/2022-06-23T15_06_25_050Z-debug-0.log
0 verbose cli /home/smoke/.nvm/versions/node/v17.4.0/bin/node /home/smoke/.nvm/versions/node/v17.4.0/bin/npm
1 info using npm@8.12.2
2 info using node@v17.4.0
3 timing npm:load:whichnode Completed in 0ms
4 timing config:load:defaults Completed in 2ms
5 timing config:load:file:/home/smoke/.nvm/versions/node/v17.4.0/lib/node_modules/npm/npmrc Completed in 2ms
6 timing config:load:builtin Completed in 3ms
7 timing config:load:cli Completed in 2ms
8 timing config:load:env Completed in 1ms
9 timing config:load:file:/home/smoke/Documents/wsl_dev/testing/genelookup/q2view/.npmrc Completed in 1ms
10 timing config:load:project Completed in 17ms
11 timing config:load:file:/home/smoke/.npmrc Completed in 2ms
12 timing config:load:user Completed in 2ms
13 timing config:load:file:/home/smoke/.nvm/versions/node/v17.4.0/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:validate Completed in 3ms
16 timing config:load:credentials Completed in 1ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 34ms
19 timing npm:load:configload Completed in 34ms
20 timing npm:load:mkdirpcache Completed in 2ms
21 timing npm:load:mkdirplogs Completed in 2ms
22 verbose title npm install
23 verbose argv "install"
24 timing npm:load:setTitle Completed in 1ms
25 timing config:load:flatten Completed in 3ms
26 timing npm:load:display Completed in 5ms
27 verbose logfile logs-max:10 dir:/home/smoke/.npm/_logs
28 verbose logfile /home/smoke/.npm/_logs/2022-06-23T15_06_25_050Z-debug-0.log
29 timing npm:load:logFile Completed in 7ms
30 timing npm:load:timers Completed in 0ms
31 timing npm:load:configScope Completed in 0ms
32 timing npm:load Completed in 53ms
33 timing arborist:ctor Completed in 1ms
34 silly logfile start cleaning logs, removing 1 files
35 silly logfile done cleaning log files
36 timing arborist:ctor Completed in 0ms
37 timing idealTree:init Completed in 35ms
38 timing idealTree:userRequests Completed in 0ms
39 silly idealTree buildDeps
40 silly fetch manifest babel-polyfill@^6.16.0
41 http fetch GET 200 https://registry.npmjs.org/babel-polyfill 996ms (cache revalidated)
42 silly fetch manifest bootstrap@^3.3.7
43 http fetch GET 200 https://registry.npmjs.org/bootstrap 295ms (cache revalidated)
44 silly fetch manifest cytoscape@^2.7.10
45 http fetch GET 200 https://registry.npmjs.org/cytoscape 1987ms (cache updated)
46 silly fetch manifest extract-text-webpack-plugin@^1.0.1
47 http fetch GET 200 https://registry.npmjs.org/extract-text-webpack-plugin 363ms (cache revalidated)
48 silly fetch manifest webpack@^1.13.2
49 http fetch GET 200 https://registry.npmjs.org/webpack 435ms (cache revalidated)
50 silly fetch manifest handlebars@^4.0.5
51 http fetch GET 200 https://registry.npmjs.org/handlebars 156ms (cache revalidated)
52 silly fetch manifest handlebars-loader@^1.4.0
53 http fetch GET 200 https://registry.npmjs.org/handlebars-loader 497ms (cache revalidated)
54 silly fetch manifest html-webpack-plugin@^2.22.0
55 http fetch GET 200 https://registry.npmjs.org/html-webpack-plugin 127ms (cache revalidated)
56 silly fetch manifest js-yaml@^3.7.0
57 http fetch GET 200 https://registry.npmjs.org/js-yaml 154ms (cache revalidated)
58 silly fetch manifest jszip@^3.1.2
59 http fetch GET 200 https://registry.npmjs.org/jszip 158ms (cache revalidated)
60 silly fetch manifest lodash@^4.16.4
61 http fetch GET 200 https://registry.npmjs.org/lodash 167ms (cache revalidated)
62 silly fetch manifest node-uuid@^1.4.7
63 http fetch GET 200 https://registry.npmjs.org/node-uuid 146ms (cache updated)
64 silly fetch manifest query-string@^4.2.3
65 http fetch GET 200 https://registry.npmjs.org/query-string 152ms (cache revalidated)
66 silly fetch manifest react@^15.3.2
67 http fetch GET 200 https://registry.npmjs.org/react 1635ms (cache updated)
68 silly fetch manifest react-bootstrap@^0.30.5
69 http fetch GET 200 https://registry.npmjs.org/react-bootstrap 484ms (cache revalidated)
70 silly fetch manifest react-dom@^15.3.2
71 http fetch GET 200 https://registry.npmjs.org/react-dom 1304ms (cache updated)
72 silly fetch manifest react-dropzone@^3.13.2
73 http fetch GET 200 https://registry.npmjs.org/react-dropzone 163ms (cache revalidated)
74 silly fetch manifest react-github-fork-ribbon@^0.5.0
75 http fetch GET 200 https://registry.npmjs.org/react-github-fork-ribbon 1183ms (cache revalidated)
76 silly fetch manifest react-json-tree@^0.10.0
77 http fetch GET 200 https://registry.npmjs.org/react-json-tree 198ms (cache revalidated)
78 silly fetch manifest react-redux@^4.4.5
79 http fetch GET 200 https://registry.npmjs.org/react-redux 172ms (cache revalidated)
80 silly fetch manifest redux@^3.6.0
81 http fetch GET 200 https://registry.npmjs.org/redux 206ms (cache revalidated)
82 silly fetch manifest react-router@^3.0.0
83 http fetch GET 200 https://registry.npmjs.org/react-router 354ms (cache updated)
84 silly fetch manifest react-router-redux@^4.0.6
85 http fetch GET 200 https://registry.npmjs.org/react-router-redux 150ms (cache revalidated)
86 silly fetch manifest redux-thunk@^2.1.0
87 http fetch GET 200 https://registry.npmjs.org/redux-thunk 176ms (cache revalidated)
88 silly fetch manifest redux@^4
89 timing idealTree Completed in 11940ms
90 timing command:install Completed in 11969ms
91 verbose stack Error: unable to resolve dependency tree
91 verbose stack     at Arborist.[failPeerConflict] (/home/smoke/.nvm/versions/node/v17.4.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1428:25)
91 verbose stack     at Arborist.[loadPeerSet] (/home/smoke/.nvm/versions/node/v17.4.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1394:34)
91 verbose stack     at async Arborist.[buildDepStep] (/home/smoke/.nvm/versions/node/v17.4.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:976:11)
91 verbose stack     at async Arborist.buildIdealTree (/home/smoke/.nvm/versions/node/v17.4.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:218:7)
91 verbose stack     at async Promise.all (index 1)
91 verbose stack     at async Arborist.reify (/home/smoke/.nvm/versions/node/v17.4.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:153:5)
91 verbose stack     at async Install.exec (/home/smoke/.nvm/versions/node/v17.4.0/lib/node_modules/npm/lib/commands/install.js:156:5)
91 verbose stack     at async module.exports (/home/smoke/.nvm/versions/node/v17.4.0/lib/node_modules/npm/lib/cli.js:78:5)
92 verbose cwd /home/smoke/Documents/wsl_dev/testing/genelookup/q2view
93 verbose Linux 5.10.60.1-microsoft-standard-WSL2
94 verbose node v17.4.0
95 verbose npm  v8.12.2
96 error code ERESOLVE
97 error ERESOLVE unable to resolve dependency tree
98 error
99 error While resolving: q2view@0.0.0
99 error Found: redux@3.7.2
99 error node_modules/redux
99 error   redux@"^3.6.0" from the root project
99 error
99 error Could not resolve dependency:
99 error peer redux@"^4" from redux-thunk@2.4.1
99 error node_modules/redux-thunk
99 error   redux-thunk@"^2.1.0" from the root project
99 error
99 error Fix the upstream dependency conflict, or retry
99 error this command with --force, or --legacy-peer-deps
99 error to accept an incorrect (and potentially broken) dependency resolution.
99 error
99 error See /home/smoke/.npm/eresolve-report.txt for a full report.
100 verbose exit 1
101 timing npm Completed in 12198ms
102 verbose unfinished npm timer reify 1655996785265
103 verbose unfinished npm timer reify:loadTrees 1655996785289
104 verbose unfinished npm timer idealTree:buildDeps 1655996785327
105 verbose unfinished npm timer idealTree:#root 1655996785328
106 verbose code 1
107 error A complete log of this run can be found in:
107 error     /home/smoke/.npm/_logs/2022-06-23T15_06_25_050Z-debug-0.log
```

**Comment by devqueue** [comment]
Same issue

**Comment by gregcaporaso** [comment]
This is one of several known issues with the build at the moment. We plan to address this for the 2023.11 release of QIIME 2 under issue #128.
